# Generated by Django 5.0.3 on 2024-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200, unique=True)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
            ],
        ),
    ]
